function [logLik, Kalman] = KalmanAll(SSM, Y)
%KalmanAll returns the log-likelihood for Y(:,1:T) and a Kalman structure
%   -SSM is a state-space model structure for Y(:,:)
    
    % Kalman filtering
    [Kalman.Filtered,...
     Kalman.FilteredCov,...
     Kalman.Predicted,...
     Kalman.PredictedCov,...
     logLik] = KalmanFilter(Y,...
                           SSM.TranMX,...
                           SSM.DistMean,...
                           SSM.DistCov,...
                           SSM.MeasMX,...
                           SSM.ObseCov,...
                           SSM.StateMean0,...
                           SSM.StateCov0);
    
    % MLE
    if nargout == 1
        return
    end
    
    Kalman.logLik = logLik;
    
    
    % Fixed interval smoothing
    [Kalman.Smoothed,...
     Kalman.SmoothedCov,...
     Kalman.Smoothed0,...
     Kalman.SmoothedCov0,...
     Kalman.ConvMinus] = FixedIntervalSmoother(Kalman.Filtered,...
                                               Kalman.FilteredCov,...
                                               Kalman.Predicted,...
                                               Kalman.PredictedCov,...
                                               SSM.TranMX,...
                                               SSM.StateMean0,...
                                               SSM.StateCov0);
end

