function [logLik, Kalman2Step] = DSS2Step(SSM, Y)
%UNTITLED6 Summary of this function goes here
%   Detailed explanation goes here
    
    % set-up
    nstep = 2;
    [n, ~] = size(Y);
    TranMX = SSM.TranMX;
    DistMean = SSM.DistMean;
    DistCov = SSM.DistCov;
    MeasMX = SSM.MeasMX;
    ObseCov = SSM.ObseCov;
    State0 = SSM.StateMean0;
    StateCov0 = SSM.StateCov0;
    logLik = 0.0;
    
    % preallocation
    Kalman = struct('Filtered', {}, ...
                    'FilteredCov', {}, ...
                    'Predicted', {}, ...
                    'PredictedCov', {}, ...
                    'logLik', {}, ...
                    'Smoothed', {}, ...
                    'SmoothedCov', {}, ...
                    'Smoothed0', {}, ...
                    'SmoothedCov0', {}, ...
                    'ConvMinus', {});
    Kalman2Step = repmat(Kalman, nstep, 1);
   
    for step=1:nstep
        % get the information at this step
        if step == 1
            InfoUse = 1:n-1;
        else
            InfoUse = n;
        end
        
        YInfoUse = Y(InfoUse, :);
        MeasMXInfoUse = MeasMX(InfoUse,:,:);
        ObseCovInfoUse = ObseCov(InfoUse,InfoUse,:);
        [Kalman2Step(step),...
         TranMX,...
         DistMean,...
         DistCov,...
         State0,...
         StateCov0] = DSSUpdate(YInfoUse,...
                                TranMX,...
                                DistMean,...
                                DistCov,...
                                MeasMXInfoUse,...
                                ObseCovInfoUse,...
                                State0,...
                                StateCov0);
                            
        logLik = logLik + Kalman2Step(step).logLik;
    end
    
end

