function [logLik, KalmanFull] = DSSFull(SSM, Y)
%DSSFULL computes the dynamic state space model in full updating process
% Description:
%
% In every step, one subject is processed. see Guo (2003)
%
% Input Arguments:
%   
%   Information: Y
%   Initial state space model structure: SSM
%
% Output Arguments:
%
%   logLik - log-likelihood for Y(:,:)
%   KalmanFull - n-by-1 Kalman structure array
    
    % set-up
    [nstep, ~] = size(Y);
    TranMX = SSM.TranMX;
    DistMean = SSM.DistMean;
    DistCov = SSM.DistCov;
    MeasMX = SSM.MeasMX;
    ObseCov = SSM.ObseCov;
    State0 = SSM.StateMean0;
    StateCov0 = SSM.StateCov0;
    logLik = 0.0;
    
    % preallocation
    Kalman = struct('Filtered', {}, ...
                    'FilteredCov', {}, ...
                    'Predicted', {}, ...
                    'PredictedCov', {}, ...
                    'logLik', {}, ...
                    'Smoothed', {}, ...
                    'SmoothedCov', {}, ...
                    'Smoothed0', {}, ...
                    'SmoothedCov0', {}, ...
                    'ConvMinus', {});
    KalmanFull = repmat(Kalman, nstep, 1);
   
    for step=1:nstep
        InfoUse = step;
        YInfoUse = Y(InfoUse, :);
        MeasMXInfoUse = MeasMX(InfoUse,:,:);
        ObseCovInfoUse = ObseCov(InfoUse,InfoUse,:);
        [KalmanFull(step),...
         TranMX,...
         DistMean,...
         DistCov,...
         State0,...
         StateCov0] = DSSUpdate(YInfoUse,...
                                TranMX,...
                                DistMean,...
                                DistCov,...
                                MeasMXInfoUse,...
                                ObseCovInfoUse,...
                                State0,...
                                StateCov0);
                            
        logLik = logLik + KalmanFull(step).logLik;
    end
    
end

