function [Kalman, TranMX, DistMean, DistCov, State0, StateCov0] =...
    DSSUpdate(Y, TranMX, DistMean, DistCov, MeasMX, ObseCov, State0, StateCov0)
%UNTITLED5 Summary of this function goes here
%   Detailed explanation goes here
    
    % Kalman filter
    [Kalman.Filtered,...
     Kalman.FilteredCov,...
     Kalman.Predicted,...
     Kalman.PredictedCov,...
     Kalman.logLik] = KalmanFilter(Y, ...
                                   TranMX, ...
                                   DistMean, ...
                                   DistCov, ...
                                   MeasMX, ...
                                   ObseCov, ...
                                   State0, ...
                                   StateCov0);
    % Fixed interval smoother
    [Kalman.Smoothed,...
     Kalman.SmoothedCov,...
     Kalman.Smoothed0,...
     Kalman.SmoothedCov0,...
     Kalman.ConvMinus] = FixedIntervalSmoother(Kalman.Filtered,...
                                               Kalman.FilteredCov,...
                                               Kalman.Predicted,...
                                               Kalman.PredictedCov,...
                                               TranMX,...
                                               State0,...
                                               StateCov0);    
    % Dynamic prior construction
    [TranMX,...
     DistMean, ...
     DistCov, ...
     State0, ...
     StateCov0] = PriorConstruction(Kalman.Smoothed,...
                                    Kalman.SmoothedCov,...
                                    Kalman.Smoothed0,...
                                    Kalman.SmoothedCov0,...
                                    Kalman.ConvMinus);

end

