function [Kalman, TranMX, DistMean, DistCov, State0, StateCov0] =...
    DSSUpdate(Y, TranMX, DistMean, DistCov, MeasMX, ObseCov, State0, StateCov0)
%DSSUPDATE computes one-step condtional state-space model and update priors
% Description:
%
% For every subject, the filtered/smoothed states and prior information are
% updated. see Guo (2003)
%
% Input Arguments:
%   
%   Information - Y
%   Priors - TranMX, DistMean, DistCov, State0, StateCov0
%   Measurement - MeasMX, ObseCov 
%
% Output Arguments:
%
%   Kalman - a Kalman structure containing filtering and smoothing
%   Priors - TranMX, DistMean, DistCov, State0, StateCov0
    
    % Kalman filter
    [Kalman.Filtered,...
     Kalman.FilteredCov,...
     Kalman.Predicted,...
     Kalman.PredictedCov,...
     Kalman.logLik] = KalmanFilter(Y, ...
                                   TranMX, ...
                                   DistMean, ...
                                   DistCov, ...
                                   MeasMX, ...
                                   ObseCov, ...
                                   State0, ...
                                   StateCov0);
    % Fixed interval smoother
    [Kalman.Smoothed,...
     Kalman.SmoothedCov,...
     Kalman.Smoothed0,...
     Kalman.SmoothedCov0,...
     Kalman.ConvMinus] = FixedIntervalSmoother(Kalman.Filtered,...
                                               Kalman.FilteredCov,...
                                               Kalman.Predicted,...
                                               Kalman.PredictedCov,...
                                               TranMX,...
                                               State0,...
                                               StateCov0);    
    % Dynamic prior construction
    [TranMX,...
     DistMean, ...
     DistCov, ...
     State0, ...
     StateCov0] = PriorConstruction(Kalman.Smoothed,...
                                    Kalman.SmoothedCov,...
                                    Kalman.Smoothed0,...
                                    Kalman.SmoothedCov0,...
                                    Kalman.ConvMinus);

end

