%% ssm_structure
%  ssm_structure creates a state-space model object,
%  given a state-space model structure

function SSModel = ssm_structure(SSModelStruc)

    SSModel = ssm(SSModelStruc.stateTran,...
              SSModelStruc.stateDist,...
              SSModelStruc.measSens,...
              SSModelStruc.obseInnov,...
              'Mean0', SSModelStruc.Mean0,...
              'Cov0', SSModelStruc.Cov0);

end

